### ISSUE TITLE
Hello Stars,

### ISSUE THREAD

**Issue by lbough** [star-city-code-school/fenrir#2]
I'm Lisa Bough (last name pronounced Boo) yes just like ghost. I worked at UNMC for 10 years and was laid off last January.  New technology came in and decimated microarrays. That was when I decided to look for a career that allowed me to be in the control of technology instead of just using it to do work. This past year I've worked for the post office and First Data. Fill in jobs while I found the right niche for my 'inevitable take over of the world!' 'Who's with me?' Yeah, I have high goals for my sense of humor.
I have two kids Jackson, 11and Katie 9. I share custody with my ex, Sherry, while I'm in Lincoln they will be with her. 
I like to read, bike, skateboard, watch movies and take naps. Also a big fan of Omaha's music and art scene.

**Comment by andrewek** [comment]
@lbough Please append your introduction to the main "Hello" thread: https://github.com/star-city-code-school/fenrir/issues/1

Thanks!

**Comment by webbedfooty** [comment]
This is Patrick aka Webbed Footy

I think I got this by mistake unless you sent to all

**Comment by andrewek** [comment]
GitHub issues go to everyone by default. If you want to change that behavior, head to the Repository page and click the "Watch" button to indicate that you're no longer watching.

![screen shot 2016-02-16 at 9 23 29 pm](https://cloud.githubusercontent.com/assets/714518/13098996/a234fc4a-d4f3-11e5-9da7-cbe4c0c764d5.png)

**Comment by webbedfooty** [comment]
Gotcha – just wanted to make sure the intended did get it
