### ISSUE TITLE
Week 05, Day 01 - Homework C

### ISSUE THREAD

**Issue by andrewek** [star-city-code-school/fenrir#44]
What questions do you have so far about Sinatra and web applications? What would you like to build? What would you like to do that you are not yet able to do? I'll do a series of mini-sessions this week, as well as some pair-programming time.

Come prepared tomorrow morning with questions, or tack them onto this issue.

**Comment by webbedfooty** [comment]
Only if these are worth reviewing; concepts that we'll need a firm understanding for future projects:
-Assert/Refute
-Getters/Setters
-Layout file/Schema file
-Setting up CSS
-Setting up Heroku
-Show maybe one or two ways to do the Check Out Book process
