### ISSUE TITLE
Week 05: Weekend Homework

### ISSUE THREAD

**Issue by andrewek** [star-city-code-school/fenrir#46]
You have two major tasks this weekend:

1. Finish up your project to the best of your ability
2. Become comfortable enough with HTML and CSS that you can at least work with it. There's no need to memorize everything -- you only need to learn enough that you know how to set things up and what to google for (i.e. you should learn some of the vocabulary).

Here are some resources for HTML and CSS:

+ https://www.codecademy.com/learn/web
+ https://www.khanacademy.org/computing/computer-programming/html-css
+ http://www.htmldog.com/guides/css/beginner/

Our big task for next week is using Bootstrap and some custom CSS for styling

If you're already very comfortable with HTML and CSS, consider doing some reading about one or more of the following:

+ Object Oriented CSS (this is the technique I use)
+ BEM-style CSS
+ [Flexbox](http://flexboxfroggy.com/)
+ SASS

Ultimately, we'll want to move to component-oriented CSS. But it'll take us a while to get there. You have to become conversant in regular CSS first.

## How to Practice 

If you want to practice your HTML and CSS skills, use a timed drill:

1. Pick a web page (or an element of a page)
2. Open your text editor and create a blank HTML and a blank CSS document
3. Set a timer for 60-90 minutes
4. Build as much of that page as you can in the time provided. Use placeholder text and [placeholder images](http://placekitten.com/) for content. Don't worry about anything other than trying to make what's on your screen look like the page you're trying to build.

Do this 15-30 times and you'll be pretty good at CSS, most likely!

We'll talk next week about common CSS tasks.

**Comment by jaybernal** [comment]
Here is a good book for learning flexbox.
https://starcitycodeschool.slack.com/files/jay_bernal/F10DHT010/unraveling_flexboxv.pdf
