### ISSUE TITLE
SHOUT

### ISSUE THREAD

**Issue by Rynium** [star-city-code-school/fenrir#57]
When clicked, the link prompts the user for their name, then greets the person in a shouty fashion with an alert (and what an alert!). If I input my name as Andrew, it should output HELLO, ANDREW!!! (or something like that).

**Comment by andrewek** [comment]
Ryan, you might want to add this issue to your repo: https://github.com/Rynium/w07-d01-js-exercises

**Comment by Rynium** [comment]
Yes accidentally added that and had no way to close it.
